# Generated by Django 5.1.5 on 2025-02-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_faq_answer_ar_faq_answer_de_faq_answer_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_ar',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_de',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_es',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_fr',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_it',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_ja',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_pt',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_zh',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ar',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_de',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_es',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_fr',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_it',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ja',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_pt',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_zh',
        ),
    ]
