# Generated by Django 5.1.5 on 2025-02-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_remove_faq_answer_ar_remove_faq_answer_de_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
