# Generated by Django 5.1.5 on 2025-02-02 09:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_faq_answer_es_faq_answer_fr_faq_question_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer_es',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_fr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
