# Generated by Django 5.1.5 on 2025-02-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_faq_answer_ar_faq_answer_de_faq_answer_it_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_zh',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_zh',
        ),
    ]
